


.PHONY: all
all: design_symb_sync_filters

.PHONY: design_symb_sync_filters
design_symb_sync_filters:
	@echo "Designing Symbol Synchronization filters!"
	@cd coeffs_generators && octave design_symb_sync_filters.m
	@echo "Done!"

