-- -------------------------------------------------------------
--
-- Module: hdlcoder_pulse_shaping_fir
-- Generated by MATLAB(R) 8.1 and the Filter Design HDL Coder 2.9.3.
-- Generated on: 2020-09-23 05:37:16
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- Name: hdlcoder_pulse_shaping_fir
-- TestBenchName: hdlcoder_pulse_shaping_fir_tb

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Multipliers           : 127
-- Folding Factor        : 1
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Filter (real)
-- -------------------------------
-- Filter Structure  : Direct-Form FIR
-- Filter Length     : 127
-- Stable            : Yes
-- Linear Phase      : Yes (Type 1)
-- Arithmetic        : fixed
-- Numerator         : s16,14 -> [-2 2)
-- Input             : s2,0 -> [-2 2)
-- Filter Internals  : Specify Precision
--   Output          : s10,8 -> [-2 2)
--   Product         : s31,29 -> [-2 2)
--   Accumulator     : s35,29 -> [-32 32)
--   Round Mode      : convergent
--   Overflow Mode   : wrap
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY hdlcoder_pulse_shaping_fir IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(1 DOWNTO 0); -- sfix2
         filter_out                      :   OUT   std_logic_vector(9 DOWNTO 0)  -- sfix10_En8
         );

END hdlcoder_pulse_shaping_fir;


----------------------------------------------------------------
--Module Architecture: hdlcoder_pulse_shaping_fir
----------------------------------------------------------------
ARCHITECTURE rtl OF hdlcoder_pulse_shaping_fir IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(1 DOWNTO 0); -- sfix2
  -- Constants
  CONSTANT coeff1                         : signed(15 DOWNTO 0) := to_signed(-142, 16); -- sfix16_En14
  CONSTANT coeff2                         : signed(15 DOWNTO 0) := to_signed(-125, 16); -- sfix16_En14
  CONSTANT coeff3                         : signed(15 DOWNTO 0) := to_signed(-96, 16); -- sfix16_En14
  CONSTANT coeff4                         : signed(15 DOWNTO 0) := to_signed(-55, 16); -- sfix16_En14
  CONSTANT coeff5                         : signed(15 DOWNTO 0) := to_signed(-6, 16); -- sfix16_En14
  CONSTANT coeff6                         : signed(15 DOWNTO 0) := to_signed(48, 16); -- sfix16_En14
  CONSTANT coeff7                         : signed(15 DOWNTO 0) := to_signed(103, 16); -- sfix16_En14
  CONSTANT coeff8                         : signed(15 DOWNTO 0) := to_signed(154, 16); -- sfix16_En14
  CONSTANT coeff9                         : signed(15 DOWNTO 0) := to_signed(197, 16); -- sfix16_En14
  CONSTANT coeff10                        : signed(15 DOWNTO 0) := to_signed(227, 16); -- sfix16_En14
  CONSTANT coeff11                        : signed(15 DOWNTO 0) := to_signed(241, 16); -- sfix16_En14
  CONSTANT coeff12                        : signed(15 DOWNTO 0) := to_signed(237, 16); -- sfix16_En14
  CONSTANT coeff13                        : signed(15 DOWNTO 0) := to_signed(214, 16); -- sfix16_En14
  CONSTANT coeff14                        : signed(15 DOWNTO 0) := to_signed(172, 16); -- sfix16_En14
  CONSTANT coeff15                        : signed(15 DOWNTO 0) := to_signed(114, 16); -- sfix16_En14
  CONSTANT coeff16                        : signed(15 DOWNTO 0) := to_signed(44, 16); -- sfix16_En14
  CONSTANT coeff17                        : signed(15 DOWNTO 0) := to_signed(-33, 16); -- sfix16_En14
  CONSTANT coeff18                        : signed(15 DOWNTO 0) := to_signed(-110, 16); -- sfix16_En14
  CONSTANT coeff19                        : signed(15 DOWNTO 0) := to_signed(-181, 16); -- sfix16_En14
  CONSTANT coeff20                        : signed(15 DOWNTO 0) := to_signed(-237, 16); -- sfix16_En14
  CONSTANT coeff21                        : signed(15 DOWNTO 0) := to_signed(-273, 16); -- sfix16_En14
  CONSTANT coeff22                        : signed(15 DOWNTO 0) := to_signed(-284, 16); -- sfix16_En14
  CONSTANT coeff23                        : signed(15 DOWNTO 0) := to_signed(-266, 16); -- sfix16_En14
  CONSTANT coeff24                        : signed(15 DOWNTO 0) := to_signed(-216, 16); -- sfix16_En14
  CONSTANT coeff25                        : signed(15 DOWNTO 0) := to_signed(-138, 16); -- sfix16_En14
  CONSTANT coeff26                        : signed(15 DOWNTO 0) := to_signed(-33, 16); -- sfix16_En14
  CONSTANT coeff27                        : signed(15 DOWNTO 0) := to_signed(90, 16); -- sfix16_En14
  CONSTANT coeff28                        : signed(15 DOWNTO 0) := to_signed(223, 16); -- sfix16_En14
  CONSTANT coeff29                        : signed(15 DOWNTO 0) := to_signed(354, 16); -- sfix16_En14
  CONSTANT coeff30                        : signed(15 DOWNTO 0) := to_signed(472, 16); -- sfix16_En14
  CONSTANT coeff31                        : signed(15 DOWNTO 0) := to_signed(562, 16); -- sfix16_En14
  CONSTANT coeff32                        : signed(15 DOWNTO 0) := to_signed(612, 16); -- sfix16_En14
  CONSTANT coeff33                        : signed(15 DOWNTO 0) := to_signed(610, 16); -- sfix16_En14
  CONSTANT coeff34                        : signed(15 DOWNTO 0) := to_signed(548, 16); -- sfix16_En14
  CONSTANT coeff35                        : signed(15 DOWNTO 0) := to_signed(419, 16); -- sfix16_En14
  CONSTANT coeff36                        : signed(15 DOWNTO 0) := to_signed(223, 16); -- sfix16_En14
  CONSTANT coeff37                        : signed(15 DOWNTO 0) := to_signed(-37, 16); -- sfix16_En14
  CONSTANT coeff38                        : signed(15 DOWNTO 0) := to_signed(-351, 16); -- sfix16_En14
  CONSTANT coeff39                        : signed(15 DOWNTO 0) := to_signed(-706, 16); -- sfix16_En14
  CONSTANT coeff40                        : signed(15 DOWNTO 0) := to_signed(-1081, 16); -- sfix16_En14
  CONSTANT coeff41                        : signed(15 DOWNTO 0) := to_signed(-1453, 16); -- sfix16_En14
  CONSTANT coeff42                        : signed(15 DOWNTO 0) := to_signed(-1794, 16); -- sfix16_En14
  CONSTANT coeff43                        : signed(15 DOWNTO 0) := to_signed(-2074, 16); -- sfix16_En14
  CONSTANT coeff44                        : signed(15 DOWNTO 0) := to_signed(-2261, 16); -- sfix16_En14
  CONSTANT coeff45                        : signed(15 DOWNTO 0) := to_signed(-2325, 16); -- sfix16_En14
  CONSTANT coeff46                        : signed(15 DOWNTO 0) := to_signed(-2240, 16); -- sfix16_En14
  CONSTANT coeff47                        : signed(15 DOWNTO 0) := to_signed(-1980, 16); -- sfix16_En14
  CONSTANT coeff48                        : signed(15 DOWNTO 0) := to_signed(-1529, 16); -- sfix16_En14
  CONSTANT coeff49                        : signed(15 DOWNTO 0) := to_signed(-877, 16); -- sfix16_En14
  CONSTANT coeff50                        : signed(15 DOWNTO 0) := to_signed(-22, 16); -- sfix16_En14
  CONSTANT coeff51                        : signed(15 DOWNTO 0) := to_signed(1030, 16); -- sfix16_En14
  CONSTANT coeff52                        : signed(15 DOWNTO 0) := to_signed(2261, 16); -- sfix16_En14
  CONSTANT coeff53                        : signed(15 DOWNTO 0) := to_signed(3645, 16); -- sfix16_En14
  CONSTANT coeff54                        : signed(15 DOWNTO 0) := to_signed(5149, 16); -- sfix16_En14
  CONSTANT coeff55                        : signed(15 DOWNTO 0) := to_signed(6730, 16); -- sfix16_En14
  CONSTANT coeff56                        : signed(15 DOWNTO 0) := to_signed(8341, 16); -- sfix16_En14
  CONSTANT coeff57                        : signed(15 DOWNTO 0) := to_signed(9930, 16); -- sfix16_En14
  CONSTANT coeff58                        : signed(15 DOWNTO 0) := to_signed(11446, 16); -- sfix16_En14
  CONSTANT coeff59                        : signed(15 DOWNTO 0) := to_signed(12834, 16); -- sfix16_En14
  CONSTANT coeff60                        : signed(15 DOWNTO 0) := to_signed(14047, 16); -- sfix16_En14
  CONSTANT coeff61                        : signed(15 DOWNTO 0) := to_signed(15040, 16); -- sfix16_En14
  CONSTANT coeff62                        : signed(15 DOWNTO 0) := to_signed(15777, 16); -- sfix16_En14
  CONSTANT coeff63                        : signed(15 DOWNTO 0) := to_signed(16231, 16); -- sfix16_En14
  CONSTANT coeff64                        : signed(15 DOWNTO 0) := to_signed(16384, 16); -- sfix16_En14
  CONSTANT coeff65                        : signed(15 DOWNTO 0) := to_signed(16231, 16); -- sfix16_En14
  CONSTANT coeff66                        : signed(15 DOWNTO 0) := to_signed(15777, 16); -- sfix16_En14
  CONSTANT coeff67                        : signed(15 DOWNTO 0) := to_signed(15040, 16); -- sfix16_En14
  CONSTANT coeff68                        : signed(15 DOWNTO 0) := to_signed(14047, 16); -- sfix16_En14
  CONSTANT coeff69                        : signed(15 DOWNTO 0) := to_signed(12834, 16); -- sfix16_En14
  CONSTANT coeff70                        : signed(15 DOWNTO 0) := to_signed(11446, 16); -- sfix16_En14
  CONSTANT coeff71                        : signed(15 DOWNTO 0) := to_signed(9930, 16); -- sfix16_En14
  CONSTANT coeff72                        : signed(15 DOWNTO 0) := to_signed(8341, 16); -- sfix16_En14
  CONSTANT coeff73                        : signed(15 DOWNTO 0) := to_signed(6730, 16); -- sfix16_En14
  CONSTANT coeff74                        : signed(15 DOWNTO 0) := to_signed(5149, 16); -- sfix16_En14
  CONSTANT coeff75                        : signed(15 DOWNTO 0) := to_signed(3645, 16); -- sfix16_En14
  CONSTANT coeff76                        : signed(15 DOWNTO 0) := to_signed(2261, 16); -- sfix16_En14
  CONSTANT coeff77                        : signed(15 DOWNTO 0) := to_signed(1030, 16); -- sfix16_En14
  CONSTANT coeff78                        : signed(15 DOWNTO 0) := to_signed(-22, 16); -- sfix16_En14
  CONSTANT coeff79                        : signed(15 DOWNTO 0) := to_signed(-877, 16); -- sfix16_En14
  CONSTANT coeff80                        : signed(15 DOWNTO 0) := to_signed(-1529, 16); -- sfix16_En14
  CONSTANT coeff81                        : signed(15 DOWNTO 0) := to_signed(-1980, 16); -- sfix16_En14
  CONSTANT coeff82                        : signed(15 DOWNTO 0) := to_signed(-2240, 16); -- sfix16_En14
  CONSTANT coeff83                        : signed(15 DOWNTO 0) := to_signed(-2325, 16); -- sfix16_En14
  CONSTANT coeff84                        : signed(15 DOWNTO 0) := to_signed(-2261, 16); -- sfix16_En14
  CONSTANT coeff85                        : signed(15 DOWNTO 0) := to_signed(-2074, 16); -- sfix16_En14
  CONSTANT coeff86                        : signed(15 DOWNTO 0) := to_signed(-1794, 16); -- sfix16_En14
  CONSTANT coeff87                        : signed(15 DOWNTO 0) := to_signed(-1453, 16); -- sfix16_En14
  CONSTANT coeff88                        : signed(15 DOWNTO 0) := to_signed(-1081, 16); -- sfix16_En14
  CONSTANT coeff89                        : signed(15 DOWNTO 0) := to_signed(-706, 16); -- sfix16_En14
  CONSTANT coeff90                        : signed(15 DOWNTO 0) := to_signed(-351, 16); -- sfix16_En14
  CONSTANT coeff91                        : signed(15 DOWNTO 0) := to_signed(-37, 16); -- sfix16_En14
  CONSTANT coeff92                        : signed(15 DOWNTO 0) := to_signed(223, 16); -- sfix16_En14
  CONSTANT coeff93                        : signed(15 DOWNTO 0) := to_signed(419, 16); -- sfix16_En14
  CONSTANT coeff94                        : signed(15 DOWNTO 0) := to_signed(548, 16); -- sfix16_En14
  CONSTANT coeff95                        : signed(15 DOWNTO 0) := to_signed(610, 16); -- sfix16_En14
  CONSTANT coeff96                        : signed(15 DOWNTO 0) := to_signed(612, 16); -- sfix16_En14
  CONSTANT coeff97                        : signed(15 DOWNTO 0) := to_signed(562, 16); -- sfix16_En14
  CONSTANT coeff98                        : signed(15 DOWNTO 0) := to_signed(472, 16); -- sfix16_En14
  CONSTANT coeff99                        : signed(15 DOWNTO 0) := to_signed(354, 16); -- sfix16_En14
  CONSTANT coeff100                       : signed(15 DOWNTO 0) := to_signed(223, 16); -- sfix16_En14
  CONSTANT coeff101                       : signed(15 DOWNTO 0) := to_signed(90, 16); -- sfix16_En14
  CONSTANT coeff102                       : signed(15 DOWNTO 0) := to_signed(-33, 16); -- sfix16_En14
  CONSTANT coeff103                       : signed(15 DOWNTO 0) := to_signed(-138, 16); -- sfix16_En14
  CONSTANT coeff104                       : signed(15 DOWNTO 0) := to_signed(-216, 16); -- sfix16_En14
  CONSTANT coeff105                       : signed(15 DOWNTO 0) := to_signed(-266, 16); -- sfix16_En14
  CONSTANT coeff106                       : signed(15 DOWNTO 0) := to_signed(-284, 16); -- sfix16_En14
  CONSTANT coeff107                       : signed(15 DOWNTO 0) := to_signed(-273, 16); -- sfix16_En14
  CONSTANT coeff108                       : signed(15 DOWNTO 0) := to_signed(-237, 16); -- sfix16_En14
  CONSTANT coeff109                       : signed(15 DOWNTO 0) := to_signed(-181, 16); -- sfix16_En14
  CONSTANT coeff110                       : signed(15 DOWNTO 0) := to_signed(-110, 16); -- sfix16_En14
  CONSTANT coeff111                       : signed(15 DOWNTO 0) := to_signed(-33, 16); -- sfix16_En14
  CONSTANT coeff112                       : signed(15 DOWNTO 0) := to_signed(44, 16); -- sfix16_En14
  CONSTANT coeff113                       : signed(15 DOWNTO 0) := to_signed(114, 16); -- sfix16_En14
  CONSTANT coeff114                       : signed(15 DOWNTO 0) := to_signed(172, 16); -- sfix16_En14
  CONSTANT coeff115                       : signed(15 DOWNTO 0) := to_signed(214, 16); -- sfix16_En14
  CONSTANT coeff116                       : signed(15 DOWNTO 0) := to_signed(237, 16); -- sfix16_En14
  CONSTANT coeff117                       : signed(15 DOWNTO 0) := to_signed(241, 16); -- sfix16_En14
  CONSTANT coeff118                       : signed(15 DOWNTO 0) := to_signed(227, 16); -- sfix16_En14
  CONSTANT coeff119                       : signed(15 DOWNTO 0) := to_signed(197, 16); -- sfix16_En14
  CONSTANT coeff120                       : signed(15 DOWNTO 0) := to_signed(154, 16); -- sfix16_En14
  CONSTANT coeff121                       : signed(15 DOWNTO 0) := to_signed(103, 16); -- sfix16_En14
  CONSTANT coeff122                       : signed(15 DOWNTO 0) := to_signed(48, 16); -- sfix16_En14
  CONSTANT coeff123                       : signed(15 DOWNTO 0) := to_signed(-6, 16); -- sfix16_En14
  CONSTANT coeff124                       : signed(15 DOWNTO 0) := to_signed(-55, 16); -- sfix16_En14
  CONSTANT coeff125                       : signed(15 DOWNTO 0) := to_signed(-96, 16); -- sfix16_En14
  CONSTANT coeff126                       : signed(15 DOWNTO 0) := to_signed(-125, 16); -- sfix16_En14
  CONSTANT coeff127                       : signed(15 DOWNTO 0) := to_signed(-142, 16); -- sfix16_En14

  -- Signals
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 126); -- sfix2
  SIGNAL product127                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp                         : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product126                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_1                       : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product125                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_2                       : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product124                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_3                       : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product123                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_4                       : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product122                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_5                       : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product121                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_6                       : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product120                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_7                       : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product119                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_8                       : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product118                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_9                       : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product117                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_10                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product116                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_11                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product115                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_12                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product114                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_13                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product113                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_14                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product112                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_15                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product111                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_16                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product110                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_17                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product109                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_18                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product108                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_19                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product107                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_20                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product106                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_21                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product105                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_22                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product104                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_23                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product103                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_24                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product102                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_25                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product101                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_26                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product100                       : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_27                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product99                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_28                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product98                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_29                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product97                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_30                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product96                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_31                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product95                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_32                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product94                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_33                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product93                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_34                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product92                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_35                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product91                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_36                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product90                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_37                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product89                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_38                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product88                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_39                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product87                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_40                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product86                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_41                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product85                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_42                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product84                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_43                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product83                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_44                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product82                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_45                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product81                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_46                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product80                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_47                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product79                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_48                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product78                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_49                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product77                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_50                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product76                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_51                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product75                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_52                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product74                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_53                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product73                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_54                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product72                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_55                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product71                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_56                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product70                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_57                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product69                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_58                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product68                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_59                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product67                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_60                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product66                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_61                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product65                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_62                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product64                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL product63                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_63                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product62                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_64                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product61                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_65                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product60                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_66                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product59                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_67                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product58                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_68                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product57                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_69                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product56                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_70                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product55                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_71                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product54                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_72                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product53                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_73                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product52                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_74                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product51                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_75                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product50                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_76                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product49                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_77                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product48                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_78                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product47                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_79                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product46                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_80                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product45                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_81                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product44                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_82                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product43                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_83                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product42                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_84                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product41                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_85                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product40                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_86                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product39                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_87                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product38                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_88                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product37                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_89                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product36                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_90                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product35                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_91                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product34                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_92                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product33                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_93                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product32                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_94                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product31                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_95                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product30                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_96                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product29                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_97                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product28                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_98                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product27                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_99                      : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product26                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_100                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product25                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_101                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product24                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_102                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product23                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_103                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product22                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_104                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product21                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_105                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product20                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_106                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product19                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_107                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product18                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_108                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product17                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_109                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product16                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_110                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product15                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_111                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product14                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_112                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product13                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_113                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product12                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_114                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product11                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_115                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product10                        : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_116                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product9                         : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_117                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product8                         : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_118                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product7                         : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_119                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product6                         : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_120                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product5                         : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_121                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product4                         : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_122                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product3                         : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_123                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product2                         : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_124                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL product1_cast                    : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL product1                         : signed(30 DOWNTO 0); -- sfix31_En29
  SIGNAL mul_temp_125                     : signed(17 DOWNTO 0); -- sfix18_En14
  SIGNAL sum1                             : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp                         : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum2                             : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_1                       : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum3                             : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_2                       : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum4                             : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_3                       : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum5                             : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_4                       : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum6                             : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_5                       : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum7                             : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_6                       : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum8                             : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_7                       : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum9                             : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_8                       : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum10                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_9                       : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum11                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_10                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum12                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_11                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum13                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_12                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum14                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_13                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum15                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_14                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum16                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_15                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum17                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_16                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum18                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_17                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum19                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_18                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum20                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_19                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum21                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_20                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum22                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_21                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum23                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_22                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum24                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_23                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum25                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_24                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum26                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_25                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum27                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_26                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum28                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_27                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum29                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_28                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum30                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_29                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum31                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_30                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum32                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_31                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum33                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_32                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum34                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_33                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum35                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_34                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum36                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_35                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum37                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_36                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum38                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_37                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum39                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_38                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum40                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_39                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum41                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_40                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum42                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_41                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum43                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_42                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum44                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_43                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum45                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_44                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum46                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_45                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum47                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_46                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum48                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_47                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum49                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_48                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum50                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_49                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum51                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_50                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum52                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_51                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum53                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_52                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum54                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_53                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum55                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_54                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum56                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_55                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum57                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_56                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum58                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_57                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum59                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_58                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum60                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_59                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum61                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_60                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum62                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_61                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum63                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_62                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum64                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_63                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum65                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_64                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum66                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_65                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum67                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_66                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum68                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_67                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum69                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_68                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum70                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_69                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum71                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_70                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum72                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_71                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum73                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_72                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum74                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_73                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum75                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_74                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum76                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_75                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum77                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_76                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum78                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_77                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum79                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_78                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum80                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_79                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum81                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_80                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum82                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_81                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum83                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_82                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum84                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_83                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum85                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_84                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum86                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_85                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum87                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_86                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum88                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_87                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum89                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_88                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum90                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_89                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum91                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_90                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum92                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_91                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum93                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_92                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum94                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_93                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum95                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_94                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum96                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_95                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum97                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_96                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum98                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_97                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum99                            : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_98                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum100                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_99                      : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum101                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_100                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum102                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_101                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum103                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_102                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum104                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_103                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum105                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_104                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum106                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_105                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum107                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_106                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum108                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_107                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum109                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_108                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum110                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_109                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum111                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_110                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum112                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_111                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum113                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_112                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum114                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_113                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum115                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_114                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum116                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_115                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum117                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_116                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum118                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_117                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum119                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_118                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum120                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_119                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum121                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_120                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum122                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_121                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum123                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_122                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum124                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_123                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum125                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_124                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL sum126                           : signed(34 DOWNTO 0); -- sfix35_En29
  SIGNAL add_temp_125                     : signed(35 DOWNTO 0); -- sfix36_En29
  SIGNAL output_typeconvert               : signed(9 DOWNTO 0); -- sfix10_En8
  SIGNAL output_register                  : signed(9 DOWNTO 0); -- sfix10_En8


BEGIN

  -- Block Statements
  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_pipeline(0 TO 126) <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_pipeline(0) <= signed(filter_in);
        delay_pipeline(1 TO 126) <= delay_pipeline(0 TO 125);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_process;

  mul_temp <= delay_pipeline(126) * coeff127;
  product127 <= resize(mul_temp(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_1 <= delay_pipeline(125) * coeff126;
  product126 <= resize(mul_temp_1(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_2 <= delay_pipeline(124) * coeff125;
  product125 <= resize(mul_temp_2(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_3 <= delay_pipeline(123) * coeff124;
  product124 <= resize(mul_temp_3(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_4 <= delay_pipeline(122) * coeff123;
  product123 <= resize(mul_temp_4(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_5 <= delay_pipeline(121) * coeff122;
  product122 <= resize(mul_temp_5(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_6 <= delay_pipeline(120) * coeff121;
  product121 <= resize(mul_temp_6(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_7 <= delay_pipeline(119) * coeff120;
  product120 <= resize(mul_temp_7(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_8 <= delay_pipeline(118) * coeff119;
  product119 <= resize(mul_temp_8(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_9 <= delay_pipeline(117) * coeff118;
  product118 <= resize(mul_temp_9(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_10 <= delay_pipeline(116) * coeff117;
  product117 <= resize(mul_temp_10(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_11 <= delay_pipeline(115) * coeff116;
  product116 <= resize(mul_temp_11(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_12 <= delay_pipeline(114) * coeff115;
  product115 <= resize(mul_temp_12(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_13 <= delay_pipeline(113) * coeff114;
  product114 <= resize(mul_temp_13(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_14 <= delay_pipeline(112) * coeff113;
  product113 <= resize(mul_temp_14(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_15 <= delay_pipeline(111) * coeff112;
  product112 <= resize(mul_temp_15(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_16 <= delay_pipeline(110) * coeff111;
  product111 <= resize(mul_temp_16(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_17 <= delay_pipeline(109) * coeff110;
  product110 <= resize(mul_temp_17(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_18 <= delay_pipeline(108) * coeff109;
  product109 <= resize(mul_temp_18(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_19 <= delay_pipeline(107) * coeff108;
  product108 <= resize(mul_temp_19(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_20 <= delay_pipeline(106) * coeff107;
  product107 <= resize(mul_temp_20(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_21 <= delay_pipeline(105) * coeff106;
  product106 <= resize(mul_temp_21(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_22 <= delay_pipeline(104) * coeff105;
  product105 <= resize(mul_temp_22(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_23 <= delay_pipeline(103) * coeff104;
  product104 <= resize(mul_temp_23(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_24 <= delay_pipeline(102) * coeff103;
  product103 <= resize(mul_temp_24(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_25 <= delay_pipeline(101) * coeff102;
  product102 <= resize(mul_temp_25(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_26 <= delay_pipeline(100) * coeff101;
  product101 <= resize(mul_temp_26(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_27 <= delay_pipeline(99) * coeff100;
  product100 <= resize(mul_temp_27(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_28 <= delay_pipeline(98) * coeff99;
  product99 <= resize(mul_temp_28(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_29 <= delay_pipeline(97) * coeff98;
  product98 <= resize(mul_temp_29(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_30 <= delay_pipeline(96) * coeff97;
  product97 <= resize(mul_temp_30(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_31 <= delay_pipeline(95) * coeff96;
  product96 <= resize(mul_temp_31(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_32 <= delay_pipeline(94) * coeff95;
  product95 <= resize(mul_temp_32(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_33 <= delay_pipeline(93) * coeff94;
  product94 <= resize(mul_temp_33(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_34 <= delay_pipeline(92) * coeff93;
  product93 <= resize(mul_temp_34(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_35 <= delay_pipeline(91) * coeff92;
  product92 <= resize(mul_temp_35(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_36 <= delay_pipeline(90) * coeff91;
  product91 <= resize(mul_temp_36(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_37 <= delay_pipeline(89) * coeff90;
  product90 <= resize(mul_temp_37(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_38 <= delay_pipeline(88) * coeff89;
  product89 <= resize(mul_temp_38(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_39 <= delay_pipeline(87) * coeff88;
  product88 <= resize(mul_temp_39(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_40 <= delay_pipeline(86) * coeff87;
  product87 <= resize(mul_temp_40(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_41 <= delay_pipeline(85) * coeff86;
  product86 <= resize(mul_temp_41(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_42 <= delay_pipeline(84) * coeff85;
  product85 <= resize(mul_temp_42(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_43 <= delay_pipeline(83) * coeff84;
  product84 <= resize(mul_temp_43(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_44 <= delay_pipeline(82) * coeff83;
  product83 <= resize(mul_temp_44(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_45 <= delay_pipeline(81) * coeff82;
  product82 <= resize(mul_temp_45(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_46 <= delay_pipeline(80) * coeff81;
  product81 <= resize(mul_temp_46(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_47 <= delay_pipeline(79) * coeff80;
  product80 <= resize(mul_temp_47(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_48 <= delay_pipeline(78) * coeff79;
  product79 <= resize(mul_temp_48(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_49 <= delay_pipeline(77) * coeff78;
  product78 <= resize(mul_temp_49(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_50 <= delay_pipeline(76) * coeff77;
  product77 <= resize(mul_temp_50(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_51 <= delay_pipeline(75) * coeff76;
  product76 <= resize(mul_temp_51(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_52 <= delay_pipeline(74) * coeff75;
  product75 <= resize(mul_temp_52(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_53 <= delay_pipeline(73) * coeff74;
  product74 <= resize(mul_temp_53(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_54 <= delay_pipeline(72) * coeff73;
  product73 <= resize(mul_temp_54(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_55 <= delay_pipeline(71) * coeff72;
  product72 <= resize(mul_temp_55(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_56 <= delay_pipeline(70) * coeff71;
  product71 <= resize(mul_temp_56(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_57 <= delay_pipeline(69) * coeff70;
  product70 <= resize(mul_temp_57(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_58 <= delay_pipeline(68) * coeff69;
  product69 <= resize(mul_temp_58(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_59 <= delay_pipeline(67) * coeff68;
  product68 <= resize(mul_temp_59(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_60 <= delay_pipeline(66) * coeff67;
  product67 <= resize(mul_temp_60(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_61 <= delay_pipeline(65) * coeff66;
  product66 <= resize(mul_temp_61(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_62 <= delay_pipeline(64) * coeff65;
  product65 <= resize(mul_temp_62(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  product64 <= resize(delay_pipeline(63)(1 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_63 <= delay_pipeline(62) * coeff63;
  product63 <= resize(mul_temp_63(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_64 <= delay_pipeline(61) * coeff62;
  product62 <= resize(mul_temp_64(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_65 <= delay_pipeline(60) * coeff61;
  product61 <= resize(mul_temp_65(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_66 <= delay_pipeline(59) * coeff60;
  product60 <= resize(mul_temp_66(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_67 <= delay_pipeline(58) * coeff59;
  product59 <= resize(mul_temp_67(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_68 <= delay_pipeline(57) * coeff58;
  product58 <= resize(mul_temp_68(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_69 <= delay_pipeline(56) * coeff57;
  product57 <= resize(mul_temp_69(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_70 <= delay_pipeline(55) * coeff56;
  product56 <= resize(mul_temp_70(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_71 <= delay_pipeline(54) * coeff55;
  product55 <= resize(mul_temp_71(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_72 <= delay_pipeline(53) * coeff54;
  product54 <= resize(mul_temp_72(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_73 <= delay_pipeline(52) * coeff53;
  product53 <= resize(mul_temp_73(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_74 <= delay_pipeline(51) * coeff52;
  product52 <= resize(mul_temp_74(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_75 <= delay_pipeline(50) * coeff51;
  product51 <= resize(mul_temp_75(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_76 <= delay_pipeline(49) * coeff50;
  product50 <= resize(mul_temp_76(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_77 <= delay_pipeline(48) * coeff49;
  product49 <= resize(mul_temp_77(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_78 <= delay_pipeline(47) * coeff48;
  product48 <= resize(mul_temp_78(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_79 <= delay_pipeline(46) * coeff47;
  product47 <= resize(mul_temp_79(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_80 <= delay_pipeline(45) * coeff46;
  product46 <= resize(mul_temp_80(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_81 <= delay_pipeline(44) * coeff45;
  product45 <= resize(mul_temp_81(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_82 <= delay_pipeline(43) * coeff44;
  product44 <= resize(mul_temp_82(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_83 <= delay_pipeline(42) * coeff43;
  product43 <= resize(mul_temp_83(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_84 <= delay_pipeline(41) * coeff42;
  product42 <= resize(mul_temp_84(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_85 <= delay_pipeline(40) * coeff41;
  product41 <= resize(mul_temp_85(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_86 <= delay_pipeline(39) * coeff40;
  product40 <= resize(mul_temp_86(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_87 <= delay_pipeline(38) * coeff39;
  product39 <= resize(mul_temp_87(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_88 <= delay_pipeline(37) * coeff38;
  product38 <= resize(mul_temp_88(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_89 <= delay_pipeline(36) * coeff37;
  product37 <= resize(mul_temp_89(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_90 <= delay_pipeline(35) * coeff36;
  product36 <= resize(mul_temp_90(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_91 <= delay_pipeline(34) * coeff35;
  product35 <= resize(mul_temp_91(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_92 <= delay_pipeline(33) * coeff34;
  product34 <= resize(mul_temp_92(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_93 <= delay_pipeline(32) * coeff33;
  product33 <= resize(mul_temp_93(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_94 <= delay_pipeline(31) * coeff32;
  product32 <= resize(mul_temp_94(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_95 <= delay_pipeline(30) * coeff31;
  product31 <= resize(mul_temp_95(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_96 <= delay_pipeline(29) * coeff30;
  product30 <= resize(mul_temp_96(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_97 <= delay_pipeline(28) * coeff29;
  product29 <= resize(mul_temp_97(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_98 <= delay_pipeline(27) * coeff28;
  product28 <= resize(mul_temp_98(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_99 <= delay_pipeline(26) * coeff27;
  product27 <= resize(mul_temp_99(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_100 <= delay_pipeline(25) * coeff26;
  product26 <= resize(mul_temp_100(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_101 <= delay_pipeline(24) * coeff25;
  product25 <= resize(mul_temp_101(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_102 <= delay_pipeline(23) * coeff24;
  product24 <= resize(mul_temp_102(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_103 <= delay_pipeline(22) * coeff23;
  product23 <= resize(mul_temp_103(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_104 <= delay_pipeline(21) * coeff22;
  product22 <= resize(mul_temp_104(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_105 <= delay_pipeline(20) * coeff21;
  product21 <= resize(mul_temp_105(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_106 <= delay_pipeline(19) * coeff20;
  product20 <= resize(mul_temp_106(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_107 <= delay_pipeline(18) * coeff19;
  product19 <= resize(mul_temp_107(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_108 <= delay_pipeline(17) * coeff18;
  product18 <= resize(mul_temp_108(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_109 <= delay_pipeline(16) * coeff17;
  product17 <= resize(mul_temp_109(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_110 <= delay_pipeline(15) * coeff16;
  product16 <= resize(mul_temp_110(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_111 <= delay_pipeline(14) * coeff15;
  product15 <= resize(mul_temp_111(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_112 <= delay_pipeline(13) * coeff14;
  product14 <= resize(mul_temp_112(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_113 <= delay_pipeline(12) * coeff13;
  product13 <= resize(mul_temp_113(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_114 <= delay_pipeline(11) * coeff12;
  product12 <= resize(mul_temp_114(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_115 <= delay_pipeline(10) * coeff11;
  product11 <= resize(mul_temp_115(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_116 <= delay_pipeline(9) * coeff10;
  product10 <= resize(mul_temp_116(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_117 <= delay_pipeline(8) * coeff9;
  product9 <= resize(mul_temp_117(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_118 <= delay_pipeline(7) * coeff8;
  product8 <= resize(mul_temp_118(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_119 <= delay_pipeline(6) * coeff7;
  product7 <= resize(mul_temp_119(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_120 <= delay_pipeline(5) * coeff6;
  product6 <= resize(mul_temp_120(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_121 <= delay_pipeline(4) * coeff5;
  product5 <= resize(mul_temp_121(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_122 <= delay_pipeline(3) * coeff4;
  product4 <= resize(mul_temp_122(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_123 <= delay_pipeline(2) * coeff3;
  product3 <= resize(mul_temp_123(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_124 <= delay_pipeline(1) * coeff2;
  product2 <= resize(mul_temp_124(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  product1_cast <= resize(product1, 35);

  mul_temp_125 <= delay_pipeline(0) * coeff1;
  product1 <= resize(mul_temp_125(15 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  add_temp <= resize(product1_cast, 36) + resize(product2, 36);
  sum1 <= add_temp(34 DOWNTO 0);

  add_temp_1 <= resize(sum1, 36) + resize(product3, 36);
  sum2 <= add_temp_1(34 DOWNTO 0);

  add_temp_2 <= resize(sum2, 36) + resize(product4, 36);
  sum3 <= add_temp_2(34 DOWNTO 0);

  add_temp_3 <= resize(sum3, 36) + resize(product5, 36);
  sum4 <= add_temp_3(34 DOWNTO 0);

  add_temp_4 <= resize(sum4, 36) + resize(product6, 36);
  sum5 <= add_temp_4(34 DOWNTO 0);

  add_temp_5 <= resize(sum5, 36) + resize(product7, 36);
  sum6 <= add_temp_5(34 DOWNTO 0);

  add_temp_6 <= resize(sum6, 36) + resize(product8, 36);
  sum7 <= add_temp_6(34 DOWNTO 0);

  add_temp_7 <= resize(sum7, 36) + resize(product9, 36);
  sum8 <= add_temp_7(34 DOWNTO 0);

  add_temp_8 <= resize(sum8, 36) + resize(product10, 36);
  sum9 <= add_temp_8(34 DOWNTO 0);

  add_temp_9 <= resize(sum9, 36) + resize(product11, 36);
  sum10 <= add_temp_9(34 DOWNTO 0);

  add_temp_10 <= resize(sum10, 36) + resize(product12, 36);
  sum11 <= add_temp_10(34 DOWNTO 0);

  add_temp_11 <= resize(sum11, 36) + resize(product13, 36);
  sum12 <= add_temp_11(34 DOWNTO 0);

  add_temp_12 <= resize(sum12, 36) + resize(product14, 36);
  sum13 <= add_temp_12(34 DOWNTO 0);

  add_temp_13 <= resize(sum13, 36) + resize(product15, 36);
  sum14 <= add_temp_13(34 DOWNTO 0);

  add_temp_14 <= resize(sum14, 36) + resize(product16, 36);
  sum15 <= add_temp_14(34 DOWNTO 0);

  add_temp_15 <= resize(sum15, 36) + resize(product17, 36);
  sum16 <= add_temp_15(34 DOWNTO 0);

  add_temp_16 <= resize(sum16, 36) + resize(product18, 36);
  sum17 <= add_temp_16(34 DOWNTO 0);

  add_temp_17 <= resize(sum17, 36) + resize(product19, 36);
  sum18 <= add_temp_17(34 DOWNTO 0);

  add_temp_18 <= resize(sum18, 36) + resize(product20, 36);
  sum19 <= add_temp_18(34 DOWNTO 0);

  add_temp_19 <= resize(sum19, 36) + resize(product21, 36);
  sum20 <= add_temp_19(34 DOWNTO 0);

  add_temp_20 <= resize(sum20, 36) + resize(product22, 36);
  sum21 <= add_temp_20(34 DOWNTO 0);

  add_temp_21 <= resize(sum21, 36) + resize(product23, 36);
  sum22 <= add_temp_21(34 DOWNTO 0);

  add_temp_22 <= resize(sum22, 36) + resize(product24, 36);
  sum23 <= add_temp_22(34 DOWNTO 0);

  add_temp_23 <= resize(sum23, 36) + resize(product25, 36);
  sum24 <= add_temp_23(34 DOWNTO 0);

  add_temp_24 <= resize(sum24, 36) + resize(product26, 36);
  sum25 <= add_temp_24(34 DOWNTO 0);

  add_temp_25 <= resize(sum25, 36) + resize(product27, 36);
  sum26 <= add_temp_25(34 DOWNTO 0);

  add_temp_26 <= resize(sum26, 36) + resize(product28, 36);
  sum27 <= add_temp_26(34 DOWNTO 0);

  add_temp_27 <= resize(sum27, 36) + resize(product29, 36);
  sum28 <= add_temp_27(34 DOWNTO 0);

  add_temp_28 <= resize(sum28, 36) + resize(product30, 36);
  sum29 <= add_temp_28(34 DOWNTO 0);

  add_temp_29 <= resize(sum29, 36) + resize(product31, 36);
  sum30 <= add_temp_29(34 DOWNTO 0);

  add_temp_30 <= resize(sum30, 36) + resize(product32, 36);
  sum31 <= add_temp_30(34 DOWNTO 0);

  add_temp_31 <= resize(sum31, 36) + resize(product33, 36);
  sum32 <= add_temp_31(34 DOWNTO 0);

  add_temp_32 <= resize(sum32, 36) + resize(product34, 36);
  sum33 <= add_temp_32(34 DOWNTO 0);

  add_temp_33 <= resize(sum33, 36) + resize(product35, 36);
  sum34 <= add_temp_33(34 DOWNTO 0);

  add_temp_34 <= resize(sum34, 36) + resize(product36, 36);
  sum35 <= add_temp_34(34 DOWNTO 0);

  add_temp_35 <= resize(sum35, 36) + resize(product37, 36);
  sum36 <= add_temp_35(34 DOWNTO 0);

  add_temp_36 <= resize(sum36, 36) + resize(product38, 36);
  sum37 <= add_temp_36(34 DOWNTO 0);

  add_temp_37 <= resize(sum37, 36) + resize(product39, 36);
  sum38 <= add_temp_37(34 DOWNTO 0);

  add_temp_38 <= resize(sum38, 36) + resize(product40, 36);
  sum39 <= add_temp_38(34 DOWNTO 0);

  add_temp_39 <= resize(sum39, 36) + resize(product41, 36);
  sum40 <= add_temp_39(34 DOWNTO 0);

  add_temp_40 <= resize(sum40, 36) + resize(product42, 36);
  sum41 <= add_temp_40(34 DOWNTO 0);

  add_temp_41 <= resize(sum41, 36) + resize(product43, 36);
  sum42 <= add_temp_41(34 DOWNTO 0);

  add_temp_42 <= resize(sum42, 36) + resize(product44, 36);
  sum43 <= add_temp_42(34 DOWNTO 0);

  add_temp_43 <= resize(sum43, 36) + resize(product45, 36);
  sum44 <= add_temp_43(34 DOWNTO 0);

  add_temp_44 <= resize(sum44, 36) + resize(product46, 36);
  sum45 <= add_temp_44(34 DOWNTO 0);

  add_temp_45 <= resize(sum45, 36) + resize(product47, 36);
  sum46 <= add_temp_45(34 DOWNTO 0);

  add_temp_46 <= resize(sum46, 36) + resize(product48, 36);
  sum47 <= add_temp_46(34 DOWNTO 0);

  add_temp_47 <= resize(sum47, 36) + resize(product49, 36);
  sum48 <= add_temp_47(34 DOWNTO 0);

  add_temp_48 <= resize(sum48, 36) + resize(product50, 36);
  sum49 <= add_temp_48(34 DOWNTO 0);

  add_temp_49 <= resize(sum49, 36) + resize(product51, 36);
  sum50 <= add_temp_49(34 DOWNTO 0);

  add_temp_50 <= resize(sum50, 36) + resize(product52, 36);
  sum51 <= add_temp_50(34 DOWNTO 0);

  add_temp_51 <= resize(sum51, 36) + resize(product53, 36);
  sum52 <= add_temp_51(34 DOWNTO 0);

  add_temp_52 <= resize(sum52, 36) + resize(product54, 36);
  sum53 <= add_temp_52(34 DOWNTO 0);

  add_temp_53 <= resize(sum53, 36) + resize(product55, 36);
  sum54 <= add_temp_53(34 DOWNTO 0);

  add_temp_54 <= resize(sum54, 36) + resize(product56, 36);
  sum55 <= add_temp_54(34 DOWNTO 0);

  add_temp_55 <= resize(sum55, 36) + resize(product57, 36);
  sum56 <= add_temp_55(34 DOWNTO 0);

  add_temp_56 <= resize(sum56, 36) + resize(product58, 36);
  sum57 <= add_temp_56(34 DOWNTO 0);

  add_temp_57 <= resize(sum57, 36) + resize(product59, 36);
  sum58 <= add_temp_57(34 DOWNTO 0);

  add_temp_58 <= resize(sum58, 36) + resize(product60, 36);
  sum59 <= add_temp_58(34 DOWNTO 0);

  add_temp_59 <= resize(sum59, 36) + resize(product61, 36);
  sum60 <= add_temp_59(34 DOWNTO 0);

  add_temp_60 <= resize(sum60, 36) + resize(product62, 36);
  sum61 <= add_temp_60(34 DOWNTO 0);

  add_temp_61 <= resize(sum61, 36) + resize(product63, 36);
  sum62 <= add_temp_61(34 DOWNTO 0);

  add_temp_62 <= resize(sum62, 36) + resize(product64, 36);
  sum63 <= add_temp_62(34 DOWNTO 0);

  add_temp_63 <= resize(sum63, 36) + resize(product65, 36);
  sum64 <= add_temp_63(34 DOWNTO 0);

  add_temp_64 <= resize(sum64, 36) + resize(product66, 36);
  sum65 <= add_temp_64(34 DOWNTO 0);

  add_temp_65 <= resize(sum65, 36) + resize(product67, 36);
  sum66 <= add_temp_65(34 DOWNTO 0);

  add_temp_66 <= resize(sum66, 36) + resize(product68, 36);
  sum67 <= add_temp_66(34 DOWNTO 0);

  add_temp_67 <= resize(sum67, 36) + resize(product69, 36);
  sum68 <= add_temp_67(34 DOWNTO 0);

  add_temp_68 <= resize(sum68, 36) + resize(product70, 36);
  sum69 <= add_temp_68(34 DOWNTO 0);

  add_temp_69 <= resize(sum69, 36) + resize(product71, 36);
  sum70 <= add_temp_69(34 DOWNTO 0);

  add_temp_70 <= resize(sum70, 36) + resize(product72, 36);
  sum71 <= add_temp_70(34 DOWNTO 0);

  add_temp_71 <= resize(sum71, 36) + resize(product73, 36);
  sum72 <= add_temp_71(34 DOWNTO 0);

  add_temp_72 <= resize(sum72, 36) + resize(product74, 36);
  sum73 <= add_temp_72(34 DOWNTO 0);

  add_temp_73 <= resize(sum73, 36) + resize(product75, 36);
  sum74 <= add_temp_73(34 DOWNTO 0);

  add_temp_74 <= resize(sum74, 36) + resize(product76, 36);
  sum75 <= add_temp_74(34 DOWNTO 0);

  add_temp_75 <= resize(sum75, 36) + resize(product77, 36);
  sum76 <= add_temp_75(34 DOWNTO 0);

  add_temp_76 <= resize(sum76, 36) + resize(product78, 36);
  sum77 <= add_temp_76(34 DOWNTO 0);

  add_temp_77 <= resize(sum77, 36) + resize(product79, 36);
  sum78 <= add_temp_77(34 DOWNTO 0);

  add_temp_78 <= resize(sum78, 36) + resize(product80, 36);
  sum79 <= add_temp_78(34 DOWNTO 0);

  add_temp_79 <= resize(sum79, 36) + resize(product81, 36);
  sum80 <= add_temp_79(34 DOWNTO 0);

  add_temp_80 <= resize(sum80, 36) + resize(product82, 36);
  sum81 <= add_temp_80(34 DOWNTO 0);

  add_temp_81 <= resize(sum81, 36) + resize(product83, 36);
  sum82 <= add_temp_81(34 DOWNTO 0);

  add_temp_82 <= resize(sum82, 36) + resize(product84, 36);
  sum83 <= add_temp_82(34 DOWNTO 0);

  add_temp_83 <= resize(sum83, 36) + resize(product85, 36);
  sum84 <= add_temp_83(34 DOWNTO 0);

  add_temp_84 <= resize(sum84, 36) + resize(product86, 36);
  sum85 <= add_temp_84(34 DOWNTO 0);

  add_temp_85 <= resize(sum85, 36) + resize(product87, 36);
  sum86 <= add_temp_85(34 DOWNTO 0);

  add_temp_86 <= resize(sum86, 36) + resize(product88, 36);
  sum87 <= add_temp_86(34 DOWNTO 0);

  add_temp_87 <= resize(sum87, 36) + resize(product89, 36);
  sum88 <= add_temp_87(34 DOWNTO 0);

  add_temp_88 <= resize(sum88, 36) + resize(product90, 36);
  sum89 <= add_temp_88(34 DOWNTO 0);

  add_temp_89 <= resize(sum89, 36) + resize(product91, 36);
  sum90 <= add_temp_89(34 DOWNTO 0);

  add_temp_90 <= resize(sum90, 36) + resize(product92, 36);
  sum91 <= add_temp_90(34 DOWNTO 0);

  add_temp_91 <= resize(sum91, 36) + resize(product93, 36);
  sum92 <= add_temp_91(34 DOWNTO 0);

  add_temp_92 <= resize(sum92, 36) + resize(product94, 36);
  sum93 <= add_temp_92(34 DOWNTO 0);

  add_temp_93 <= resize(sum93, 36) + resize(product95, 36);
  sum94 <= add_temp_93(34 DOWNTO 0);

  add_temp_94 <= resize(sum94, 36) + resize(product96, 36);
  sum95 <= add_temp_94(34 DOWNTO 0);

  add_temp_95 <= resize(sum95, 36) + resize(product97, 36);
  sum96 <= add_temp_95(34 DOWNTO 0);

  add_temp_96 <= resize(sum96, 36) + resize(product98, 36);
  sum97 <= add_temp_96(34 DOWNTO 0);

  add_temp_97 <= resize(sum97, 36) + resize(product99, 36);
  sum98 <= add_temp_97(34 DOWNTO 0);

  add_temp_98 <= resize(sum98, 36) + resize(product100, 36);
  sum99 <= add_temp_98(34 DOWNTO 0);

  add_temp_99 <= resize(sum99, 36) + resize(product101, 36);
  sum100 <= add_temp_99(34 DOWNTO 0);

  add_temp_100 <= resize(sum100, 36) + resize(product102, 36);
  sum101 <= add_temp_100(34 DOWNTO 0);

  add_temp_101 <= resize(sum101, 36) + resize(product103, 36);
  sum102 <= add_temp_101(34 DOWNTO 0);

  add_temp_102 <= resize(sum102, 36) + resize(product104, 36);
  sum103 <= add_temp_102(34 DOWNTO 0);

  add_temp_103 <= resize(sum103, 36) + resize(product105, 36);
  sum104 <= add_temp_103(34 DOWNTO 0);

  add_temp_104 <= resize(sum104, 36) + resize(product106, 36);
  sum105 <= add_temp_104(34 DOWNTO 0);

  add_temp_105 <= resize(sum105, 36) + resize(product107, 36);
  sum106 <= add_temp_105(34 DOWNTO 0);

  add_temp_106 <= resize(sum106, 36) + resize(product108, 36);
  sum107 <= add_temp_106(34 DOWNTO 0);

  add_temp_107 <= resize(sum107, 36) + resize(product109, 36);
  sum108 <= add_temp_107(34 DOWNTO 0);

  add_temp_108 <= resize(sum108, 36) + resize(product110, 36);
  sum109 <= add_temp_108(34 DOWNTO 0);

  add_temp_109 <= resize(sum109, 36) + resize(product111, 36);
  sum110 <= add_temp_109(34 DOWNTO 0);

  add_temp_110 <= resize(sum110, 36) + resize(product112, 36);
  sum111 <= add_temp_110(34 DOWNTO 0);

  add_temp_111 <= resize(sum111, 36) + resize(product113, 36);
  sum112 <= add_temp_111(34 DOWNTO 0);

  add_temp_112 <= resize(sum112, 36) + resize(product114, 36);
  sum113 <= add_temp_112(34 DOWNTO 0);

  add_temp_113 <= resize(sum113, 36) + resize(product115, 36);
  sum114 <= add_temp_113(34 DOWNTO 0);

  add_temp_114 <= resize(sum114, 36) + resize(product116, 36);
  sum115 <= add_temp_114(34 DOWNTO 0);

  add_temp_115 <= resize(sum115, 36) + resize(product117, 36);
  sum116 <= add_temp_115(34 DOWNTO 0);

  add_temp_116 <= resize(sum116, 36) + resize(product118, 36);
  sum117 <= add_temp_116(34 DOWNTO 0);

  add_temp_117 <= resize(sum117, 36) + resize(product119, 36);
  sum118 <= add_temp_117(34 DOWNTO 0);

  add_temp_118 <= resize(sum118, 36) + resize(product120, 36);
  sum119 <= add_temp_118(34 DOWNTO 0);

  add_temp_119 <= resize(sum119, 36) + resize(product121, 36);
  sum120 <= add_temp_119(34 DOWNTO 0);

  add_temp_120 <= resize(sum120, 36) + resize(product122, 36);
  sum121 <= add_temp_120(34 DOWNTO 0);

  add_temp_121 <= resize(sum121, 36) + resize(product123, 36);
  sum122 <= add_temp_121(34 DOWNTO 0);

  add_temp_122 <= resize(sum122, 36) + resize(product124, 36);
  sum123 <= add_temp_122(34 DOWNTO 0);

  add_temp_123 <= resize(sum123, 36) + resize(product125, 36);
  sum124 <= add_temp_123(34 DOWNTO 0);

  add_temp_124 <= resize(sum124, 36) + resize(product126, 36);
  sum125 <= add_temp_124(34 DOWNTO 0);

  add_temp_125 <= resize(sum125, 36) + resize(product127, 36);
  sum126 <= add_temp_125(34 DOWNTO 0);

  output_typeconvert <= resize(shift_right(sum126(30 DOWNTO 0) + ( "0" & (sum126(21) & NOT sum126(21) & NOT sum126(21) & NOT sum126(21) & NOT sum126(21) & NOT sum126(21) & NOT sum126(21) & NOT sum126(21) & NOT sum126(21) & NOT sum126(21) & NOT sum126(21) & NOT sum126(21) & NOT sum126(21) & NOT sum126(21) & NOT sum126(21) & NOT sum126(21) & NOT sum126(21) & NOT sum126(21) & NOT sum126(21) & NOT sum126(21) & NOT sum126(21))), 21), 10);

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= std_logic_vector(output_register);
END rtl;
