-- -------------------------------------------------------------
--
-- Module: hdlcoder_matched_filter_fir
-- Generated by MATLAB(R) 8.1 and the Filter Design HDL Coder 2.9.3.
-- Generated on: 2020-10-01 02:35:41
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- Name: hdlcoder_matched_filter_fir
-- TestBenchName: hdlcoder_matched_filter_fir_tb

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Multipliers           : 79
-- Folding Factor        : 1
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Filter (real)
-- -------------------------------
-- Filter Structure  : Direct-Form FIR
-- Filter Length     : 79
-- Stable            : Yes
-- Linear Phase      : Yes (Type 1)
-- Arithmetic        : fixed
-- Numerator         : s16,18 -> [-1.250000e-01 1.250000e-01)
-- Input             : s10,8 -> [-2 2)
-- Filter Internals  : Specify Precision
--   Output          : s10,8 -> [-2 2)
--   Product         : s31,33 -> [-1.250000e-01 1.250000e-01)
--   Accumulator     : s35,33 -> [-2 2)
--   Round Mode      : convergent
--   Overflow Mode   : wrap
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY hdlcoder_matched_filter_fir IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    std_logic_vector(9 DOWNTO 0); -- sfix10_En8
         filter_out                      :   OUT   std_logic_vector(9 DOWNTO 0)  -- sfix10_En8
         );

END hdlcoder_matched_filter_fir;


----------------------------------------------------------------
--Module Architecture: hdlcoder_matched_filter_fir
----------------------------------------------------------------
ARCHITECTURE rtl OF hdlcoder_matched_filter_fir IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF signed(9 DOWNTO 0); -- sfix10_En8
  -- Constants
  CONSTANT coeff1                         : signed(15 DOWNTO 0) := to_signed(-178, 16); -- sfix16_En18
  CONSTANT coeff2                         : signed(15 DOWNTO 0) := to_signed(-43, 16); -- sfix16_En18
  CONSTANT coeff3                         : signed(15 DOWNTO 0) := to_signed(116, 16); -- sfix16_En18
  CONSTANT coeff4                         : signed(15 DOWNTO 0) := to_signed(288, 16); -- sfix16_En18
  CONSTANT coeff5                         : signed(15 DOWNTO 0) := to_signed(458, 16); -- sfix16_En18
  CONSTANT coeff6                         : signed(15 DOWNTO 0) := to_signed(610, 16); -- sfix16_En18
  CONSTANT coeff7                         : signed(15 DOWNTO 0) := to_signed(726, 16); -- sfix16_En18
  CONSTANT coeff8                         : signed(15 DOWNTO 0) := to_signed(791, 16); -- sfix16_En18
  CONSTANT coeff9                         : signed(15 DOWNTO 0) := to_signed(789, 16); -- sfix16_En18
  CONSTANT coeff10                        : signed(15 DOWNTO 0) := to_signed(708, 16); -- sfix16_En18
  CONSTANT coeff11                        : signed(15 DOWNTO 0) := to_signed(542, 16); -- sfix16_En18
  CONSTANT coeff12                        : signed(15 DOWNTO 0) := to_signed(288, 16); -- sfix16_En18
  CONSTANT coeff13                        : signed(15 DOWNTO 0) := to_signed(-48, 16); -- sfix16_En18
  CONSTANT coeff14                        : signed(15 DOWNTO 0) := to_signed(-454, 16); -- sfix16_En18
  CONSTANT coeff15                        : signed(15 DOWNTO 0) := to_signed(-913, 16); -- sfix16_En18
  CONSTANT coeff16                        : signed(15 DOWNTO 0) := to_signed(-1398, 16); -- sfix16_En18
  CONSTANT coeff17                        : signed(15 DOWNTO 0) := to_signed(-1879, 16); -- sfix16_En18
  CONSTANT coeff18                        : signed(15 DOWNTO 0) := to_signed(-2319, 16); -- sfix16_En18
  CONSTANT coeff19                        : signed(15 DOWNTO 0) := to_signed(-2681, 16); -- sfix16_En18
  CONSTANT coeff20                        : signed(15 DOWNTO 0) := to_signed(-2923, 16); -- sfix16_En18
  CONSTANT coeff21                        : signed(15 DOWNTO 0) := to_signed(-3006, 16); -- sfix16_En18
  CONSTANT coeff22                        : signed(15 DOWNTO 0) := to_signed(-2895, 16); -- sfix16_En18
  CONSTANT coeff23                        : signed(15 DOWNTO 0) := to_signed(-2560, 16); -- sfix16_En18
  CONSTANT coeff24                        : signed(15 DOWNTO 0) := to_signed(-1977, 16); -- sfix16_En18
  CONSTANT coeff25                        : signed(15 DOWNTO 0) := to_signed(-1134, 16); -- sfix16_En18
  CONSTANT coeff26                        : signed(15 DOWNTO 0) := to_signed(-28, 16); -- sfix16_En18
  CONSTANT coeff27                        : signed(15 DOWNTO 0) := to_signed(1331, 16); -- sfix16_En18
  CONSTANT coeff28                        : signed(15 DOWNTO 0) := to_signed(2923, 16); -- sfix16_En18
  CONSTANT coeff29                        : signed(15 DOWNTO 0) := to_signed(4712, 16); -- sfix16_En18
  CONSTANT coeff30                        : signed(15 DOWNTO 0) := to_signed(6656, 16); -- sfix16_En18
  CONSTANT coeff31                        : signed(15 DOWNTO 0) := to_signed(8700, 16); -- sfix16_En18
  CONSTANT coeff32                        : signed(15 DOWNTO 0) := to_signed(10782, 16); -- sfix16_En18
  CONSTANT coeff33                        : signed(15 DOWNTO 0) := to_signed(12837, 16); -- sfix16_En18
  CONSTANT coeff34                        : signed(15 DOWNTO 0) := to_signed(14795, 16); -- sfix16_En18
  CONSTANT coeff35                        : signed(15 DOWNTO 0) := to_signed(16590, 16); -- sfix16_En18
  CONSTANT coeff36                        : signed(15 DOWNTO 0) := to_signed(18158, 16); -- sfix16_En18
  CONSTANT coeff37                        : signed(15 DOWNTO 0) := to_signed(19442, 16); -- sfix16_En18
  CONSTANT coeff38                        : signed(15 DOWNTO 0) := to_signed(20395, 16); -- sfix16_En18
  CONSTANT coeff39                        : signed(15 DOWNTO 0) := to_signed(20981, 16); -- sfix16_En18
  CONSTANT coeff40                        : signed(15 DOWNTO 0) := to_signed(21179, 16); -- sfix16_En18
  CONSTANT coeff41                        : signed(15 DOWNTO 0) := to_signed(20981, 16); -- sfix16_En18
  CONSTANT coeff42                        : signed(15 DOWNTO 0) := to_signed(20395, 16); -- sfix16_En18
  CONSTANT coeff43                        : signed(15 DOWNTO 0) := to_signed(19442, 16); -- sfix16_En18
  CONSTANT coeff44                        : signed(15 DOWNTO 0) := to_signed(18158, 16); -- sfix16_En18
  CONSTANT coeff45                        : signed(15 DOWNTO 0) := to_signed(16590, 16); -- sfix16_En18
  CONSTANT coeff46                        : signed(15 DOWNTO 0) := to_signed(14795, 16); -- sfix16_En18
  CONSTANT coeff47                        : signed(15 DOWNTO 0) := to_signed(12837, 16); -- sfix16_En18
  CONSTANT coeff48                        : signed(15 DOWNTO 0) := to_signed(10782, 16); -- sfix16_En18
  CONSTANT coeff49                        : signed(15 DOWNTO 0) := to_signed(8700, 16); -- sfix16_En18
  CONSTANT coeff50                        : signed(15 DOWNTO 0) := to_signed(6656, 16); -- sfix16_En18
  CONSTANT coeff51                        : signed(15 DOWNTO 0) := to_signed(4712, 16); -- sfix16_En18
  CONSTANT coeff52                        : signed(15 DOWNTO 0) := to_signed(2923, 16); -- sfix16_En18
  CONSTANT coeff53                        : signed(15 DOWNTO 0) := to_signed(1331, 16); -- sfix16_En18
  CONSTANT coeff54                        : signed(15 DOWNTO 0) := to_signed(-28, 16); -- sfix16_En18
  CONSTANT coeff55                        : signed(15 DOWNTO 0) := to_signed(-1134, 16); -- sfix16_En18
  CONSTANT coeff56                        : signed(15 DOWNTO 0) := to_signed(-1977, 16); -- sfix16_En18
  CONSTANT coeff57                        : signed(15 DOWNTO 0) := to_signed(-2560, 16); -- sfix16_En18
  CONSTANT coeff58                        : signed(15 DOWNTO 0) := to_signed(-2895, 16); -- sfix16_En18
  CONSTANT coeff59                        : signed(15 DOWNTO 0) := to_signed(-3006, 16); -- sfix16_En18
  CONSTANT coeff60                        : signed(15 DOWNTO 0) := to_signed(-2923, 16); -- sfix16_En18
  CONSTANT coeff61                        : signed(15 DOWNTO 0) := to_signed(-2681, 16); -- sfix16_En18
  CONSTANT coeff62                        : signed(15 DOWNTO 0) := to_signed(-2319, 16); -- sfix16_En18
  CONSTANT coeff63                        : signed(15 DOWNTO 0) := to_signed(-1879, 16); -- sfix16_En18
  CONSTANT coeff64                        : signed(15 DOWNTO 0) := to_signed(-1398, 16); -- sfix16_En18
  CONSTANT coeff65                        : signed(15 DOWNTO 0) := to_signed(-913, 16); -- sfix16_En18
  CONSTANT coeff66                        : signed(15 DOWNTO 0) := to_signed(-454, 16); -- sfix16_En18
  CONSTANT coeff67                        : signed(15 DOWNTO 0) := to_signed(-48, 16); -- sfix16_En18
  CONSTANT coeff68                        : signed(15 DOWNTO 0) := to_signed(288, 16); -- sfix16_En18
  CONSTANT coeff69                        : signed(15 DOWNTO 0) := to_signed(542, 16); -- sfix16_En18
  CONSTANT coeff70                        : signed(15 DOWNTO 0) := to_signed(708, 16); -- sfix16_En18
  CONSTANT coeff71                        : signed(15 DOWNTO 0) := to_signed(789, 16); -- sfix16_En18
  CONSTANT coeff72                        : signed(15 DOWNTO 0) := to_signed(791, 16); -- sfix16_En18
  CONSTANT coeff73                        : signed(15 DOWNTO 0) := to_signed(726, 16); -- sfix16_En18
  CONSTANT coeff74                        : signed(15 DOWNTO 0) := to_signed(610, 16); -- sfix16_En18
  CONSTANT coeff75                        : signed(15 DOWNTO 0) := to_signed(458, 16); -- sfix16_En18
  CONSTANT coeff76                        : signed(15 DOWNTO 0) := to_signed(288, 16); -- sfix16_En18
  CONSTANT coeff77                        : signed(15 DOWNTO 0) := to_signed(116, 16); -- sfix16_En18
  CONSTANT coeff78                        : signed(15 DOWNTO 0) := to_signed(-43, 16); -- sfix16_En18
  CONSTANT coeff79                        : signed(15 DOWNTO 0) := to_signed(-178, 16); -- sfix16_En18

  -- Signals
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 78); -- sfix10_En8
  SIGNAL product79                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp                         : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product78                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_1                       : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product77                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_2                       : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product76                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_3                       : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product75                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_4                       : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product74                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_5                       : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product73                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_6                       : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product72                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_7                       : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product71                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_8                       : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product70                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_9                       : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product69                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_10                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product68                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_11                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product67                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_12                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product66                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_13                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product65                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_14                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product64                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_15                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product63                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_16                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product62                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_17                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product61                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_18                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product60                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_19                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product59                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_20                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product58                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_21                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product57                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_22                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product56                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_23                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product55                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_24                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product54                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_25                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product53                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_26                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product52                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_27                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product51                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_28                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product50                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_29                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product49                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_30                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product48                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_31                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product47                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_32                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product46                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_33                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product45                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_34                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product44                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_35                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product43                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_36                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product42                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_37                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product41                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_38                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product40                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_39                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product39                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_40                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product38                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_41                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product37                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_42                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product36                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_43                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product35                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_44                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product34                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_45                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product33                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_46                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product32                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_47                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product31                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_48                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product30                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_49                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product29                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_50                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product28                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_51                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product27                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_52                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product26                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_53                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product25                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_54                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product24                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_55                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product23                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_56                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product22                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_57                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product21                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_58                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product20                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_59                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product19                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_60                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product18                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_61                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product17                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_62                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product16                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_63                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product15                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_64                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product14                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_65                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product13                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_66                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product12                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_67                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product11                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_68                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product10                        : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_69                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product9                         : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_70                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product8                         : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_71                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product7                         : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_72                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product6                         : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_73                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product5                         : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_74                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product4                         : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_75                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product3                         : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_76                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product2                         : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_77                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL product1_cast                    : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL product1                         : signed(30 DOWNTO 0); -- sfix31_En33
  SIGNAL mul_temp_78                      : signed(25 DOWNTO 0); -- sfix26_En26
  SIGNAL sum1                             : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp                         : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum2                             : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_1                       : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum3                             : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_2                       : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum4                             : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_3                       : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum5                             : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_4                       : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum6                             : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_5                       : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum7                             : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_6                       : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum8                             : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_7                       : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum9                             : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_8                       : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum10                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_9                       : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum11                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_10                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum12                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_11                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum13                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_12                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum14                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_13                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum15                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_14                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum16                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_15                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum17                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_16                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum18                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_17                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum19                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_18                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum20                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_19                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum21                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_20                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum22                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_21                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum23                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_22                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum24                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_23                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum25                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_24                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum26                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_25                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum27                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_26                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum28                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_27                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum29                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_28                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum30                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_29                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum31                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_30                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum32                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_31                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum33                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_32                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum34                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_33                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum35                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_34                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum36                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_35                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum37                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_36                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum38                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_37                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum39                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_38                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum40                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_39                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum41                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_40                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum42                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_41                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum43                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_42                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum44                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_43                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum45                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_44                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum46                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_45                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum47                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_46                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum48                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_47                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum49                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_48                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum50                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_49                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum51                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_50                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum52                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_51                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum53                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_52                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum54                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_53                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum55                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_54                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum56                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_55                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum57                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_56                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum58                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_57                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum59                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_58                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum60                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_59                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum61                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_60                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum62                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_61                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum63                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_62                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum64                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_63                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum65                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_64                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum66                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_65                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum67                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_66                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum68                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_67                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum69                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_68                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum70                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_69                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum71                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_70                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum72                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_71                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum73                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_72                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum74                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_73                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum75                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_74                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum76                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_75                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum77                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_76                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL sum78                            : signed(34 DOWNTO 0); -- sfix35_En33
  SIGNAL add_temp_77                      : signed(35 DOWNTO 0); -- sfix36_En33
  SIGNAL output_typeconvert               : signed(9 DOWNTO 0); -- sfix10_En8
  SIGNAL output_register                  : signed(9 DOWNTO 0); -- sfix10_En8


BEGIN

  -- Block Statements
  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_pipeline(0 TO 78) <= (OTHERS => (OTHERS => '0'));
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_pipeline(0) <= signed(filter_in);
        delay_pipeline(1 TO 78) <= delay_pipeline(0 TO 77);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_process;

  mul_temp <= delay_pipeline(78) * coeff79;
  product79 <= resize(mul_temp(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_1 <= delay_pipeline(77) * coeff78;
  product78 <= resize(mul_temp_1(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_2 <= delay_pipeline(76) * coeff77;
  product77 <= resize(mul_temp_2(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_3 <= delay_pipeline(75) * coeff76;
  product76 <= resize(mul_temp_3(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_4 <= delay_pipeline(74) * coeff75;
  product75 <= resize(mul_temp_4(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_5 <= delay_pipeline(73) * coeff74;
  product74 <= resize(mul_temp_5(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_6 <= delay_pipeline(72) * coeff73;
  product73 <= resize(mul_temp_6(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_7 <= delay_pipeline(71) * coeff72;
  product72 <= resize(mul_temp_7(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_8 <= delay_pipeline(70) * coeff71;
  product71 <= resize(mul_temp_8(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_9 <= delay_pipeline(69) * coeff70;
  product70 <= resize(mul_temp_9(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_10 <= delay_pipeline(68) * coeff69;
  product69 <= resize(mul_temp_10(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_11 <= delay_pipeline(67) * coeff68;
  product68 <= resize(mul_temp_11(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_12 <= delay_pipeline(66) * coeff67;
  product67 <= resize(mul_temp_12(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_13 <= delay_pipeline(65) * coeff66;
  product66 <= resize(mul_temp_13(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_14 <= delay_pipeline(64) * coeff65;
  product65 <= resize(mul_temp_14(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_15 <= delay_pipeline(63) * coeff64;
  product64 <= resize(mul_temp_15(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_16 <= delay_pipeline(62) * coeff63;
  product63 <= resize(mul_temp_16(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_17 <= delay_pipeline(61) * coeff62;
  product62 <= resize(mul_temp_17(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_18 <= delay_pipeline(60) * coeff61;
  product61 <= resize(mul_temp_18(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_19 <= delay_pipeline(59) * coeff60;
  product60 <= resize(mul_temp_19(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_20 <= delay_pipeline(58) * coeff59;
  product59 <= resize(mul_temp_20(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_21 <= delay_pipeline(57) * coeff58;
  product58 <= resize(mul_temp_21(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_22 <= delay_pipeline(56) * coeff57;
  product57 <= resize(mul_temp_22(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_23 <= delay_pipeline(55) * coeff56;
  product56 <= resize(mul_temp_23(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_24 <= delay_pipeline(54) * coeff55;
  product55 <= resize(mul_temp_24(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_25 <= delay_pipeline(53) * coeff54;
  product54 <= resize(mul_temp_25(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_26 <= delay_pipeline(52) * coeff53;
  product53 <= resize(mul_temp_26(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_27 <= delay_pipeline(51) * coeff52;
  product52 <= resize(mul_temp_27(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_28 <= delay_pipeline(50) * coeff51;
  product51 <= resize(mul_temp_28(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_29 <= delay_pipeline(49) * coeff50;
  product50 <= resize(mul_temp_29(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_30 <= delay_pipeline(48) * coeff49;
  product49 <= resize(mul_temp_30(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_31 <= delay_pipeline(47) * coeff48;
  product48 <= resize(mul_temp_31(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_32 <= delay_pipeline(46) * coeff47;
  product47 <= resize(mul_temp_32(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_33 <= delay_pipeline(45) * coeff46;
  product46 <= resize(mul_temp_33(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_34 <= delay_pipeline(44) * coeff45;
  product45 <= resize(mul_temp_34(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_35 <= delay_pipeline(43) * coeff44;
  product44 <= resize(mul_temp_35(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_36 <= delay_pipeline(42) * coeff43;
  product43 <= resize(mul_temp_36(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_37 <= delay_pipeline(41) * coeff42;
  product42 <= resize(mul_temp_37(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_38 <= delay_pipeline(40) * coeff41;
  product41 <= resize(mul_temp_38(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_39 <= delay_pipeline(39) * coeff40;
  product40 <= resize(mul_temp_39(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_40 <= delay_pipeline(38) * coeff39;
  product39 <= resize(mul_temp_40(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_41 <= delay_pipeline(37) * coeff38;
  product38 <= resize(mul_temp_41(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_42 <= delay_pipeline(36) * coeff37;
  product37 <= resize(mul_temp_42(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_43 <= delay_pipeline(35) * coeff36;
  product36 <= resize(mul_temp_43(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_44 <= delay_pipeline(34) * coeff35;
  product35 <= resize(mul_temp_44(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_45 <= delay_pipeline(33) * coeff34;
  product34 <= resize(mul_temp_45(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_46 <= delay_pipeline(32) * coeff33;
  product33 <= resize(mul_temp_46(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_47 <= delay_pipeline(31) * coeff32;
  product32 <= resize(mul_temp_47(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_48 <= delay_pipeline(30) * coeff31;
  product31 <= resize(mul_temp_48(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_49 <= delay_pipeline(29) * coeff30;
  product30 <= resize(mul_temp_49(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_50 <= delay_pipeline(28) * coeff29;
  product29 <= resize(mul_temp_50(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_51 <= delay_pipeline(27) * coeff28;
  product28 <= resize(mul_temp_51(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_52 <= delay_pipeline(26) * coeff27;
  product27 <= resize(mul_temp_52(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_53 <= delay_pipeline(25) * coeff26;
  product26 <= resize(mul_temp_53(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_54 <= delay_pipeline(24) * coeff25;
  product25 <= resize(mul_temp_54(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_55 <= delay_pipeline(23) * coeff24;
  product24 <= resize(mul_temp_55(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_56 <= delay_pipeline(22) * coeff23;
  product23 <= resize(mul_temp_56(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_57 <= delay_pipeline(21) * coeff22;
  product22 <= resize(mul_temp_57(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_58 <= delay_pipeline(20) * coeff21;
  product21 <= resize(mul_temp_58(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_59 <= delay_pipeline(19) * coeff20;
  product20 <= resize(mul_temp_59(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_60 <= delay_pipeline(18) * coeff19;
  product19 <= resize(mul_temp_60(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_61 <= delay_pipeline(17) * coeff18;
  product18 <= resize(mul_temp_61(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_62 <= delay_pipeline(16) * coeff17;
  product17 <= resize(mul_temp_62(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_63 <= delay_pipeline(15) * coeff16;
  product16 <= resize(mul_temp_63(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_64 <= delay_pipeline(14) * coeff15;
  product15 <= resize(mul_temp_64(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_65 <= delay_pipeline(13) * coeff14;
  product14 <= resize(mul_temp_65(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_66 <= delay_pipeline(12) * coeff13;
  product13 <= resize(mul_temp_66(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_67 <= delay_pipeline(11) * coeff12;
  product12 <= resize(mul_temp_67(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_68 <= delay_pipeline(10) * coeff11;
  product11 <= resize(mul_temp_68(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_69 <= delay_pipeline(9) * coeff10;
  product10 <= resize(mul_temp_69(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_70 <= delay_pipeline(8) * coeff9;
  product9 <= resize(mul_temp_70(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_71 <= delay_pipeline(7) * coeff8;
  product8 <= resize(mul_temp_71(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_72 <= delay_pipeline(6) * coeff7;
  product7 <= resize(mul_temp_72(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_73 <= delay_pipeline(5) * coeff6;
  product6 <= resize(mul_temp_73(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_74 <= delay_pipeline(4) * coeff5;
  product5 <= resize(mul_temp_74(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_75 <= delay_pipeline(3) * coeff4;
  product4 <= resize(mul_temp_75(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_76 <= delay_pipeline(2) * coeff3;
  product3 <= resize(mul_temp_76(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  mul_temp_77 <= delay_pipeline(1) * coeff2;
  product2 <= resize(mul_temp_77(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  product1_cast <= resize(product1, 35);

  mul_temp_78 <= delay_pipeline(0) * coeff1;
  product1 <= resize(mul_temp_78(23 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0', 31);

  add_temp <= resize(product1_cast, 36) + resize(product2, 36);
  sum1 <= add_temp(34 DOWNTO 0);

  add_temp_1 <= resize(sum1, 36) + resize(product3, 36);
  sum2 <= add_temp_1(34 DOWNTO 0);

  add_temp_2 <= resize(sum2, 36) + resize(product4, 36);
  sum3 <= add_temp_2(34 DOWNTO 0);

  add_temp_3 <= resize(sum3, 36) + resize(product5, 36);
  sum4 <= add_temp_3(34 DOWNTO 0);

  add_temp_4 <= resize(sum4, 36) + resize(product6, 36);
  sum5 <= add_temp_4(34 DOWNTO 0);

  add_temp_5 <= resize(sum5, 36) + resize(product7, 36);
  sum6 <= add_temp_5(34 DOWNTO 0);

  add_temp_6 <= resize(sum6, 36) + resize(product8, 36);
  sum7 <= add_temp_6(34 DOWNTO 0);

  add_temp_7 <= resize(sum7, 36) + resize(product9, 36);
  sum8 <= add_temp_7(34 DOWNTO 0);

  add_temp_8 <= resize(sum8, 36) + resize(product10, 36);
  sum9 <= add_temp_8(34 DOWNTO 0);

  add_temp_9 <= resize(sum9, 36) + resize(product11, 36);
  sum10 <= add_temp_9(34 DOWNTO 0);

  add_temp_10 <= resize(sum10, 36) + resize(product12, 36);
  sum11 <= add_temp_10(34 DOWNTO 0);

  add_temp_11 <= resize(sum11, 36) + resize(product13, 36);
  sum12 <= add_temp_11(34 DOWNTO 0);

  add_temp_12 <= resize(sum12, 36) + resize(product14, 36);
  sum13 <= add_temp_12(34 DOWNTO 0);

  add_temp_13 <= resize(sum13, 36) + resize(product15, 36);
  sum14 <= add_temp_13(34 DOWNTO 0);

  add_temp_14 <= resize(sum14, 36) + resize(product16, 36);
  sum15 <= add_temp_14(34 DOWNTO 0);

  add_temp_15 <= resize(sum15, 36) + resize(product17, 36);
  sum16 <= add_temp_15(34 DOWNTO 0);

  add_temp_16 <= resize(sum16, 36) + resize(product18, 36);
  sum17 <= add_temp_16(34 DOWNTO 0);

  add_temp_17 <= resize(sum17, 36) + resize(product19, 36);
  sum18 <= add_temp_17(34 DOWNTO 0);

  add_temp_18 <= resize(sum18, 36) + resize(product20, 36);
  sum19 <= add_temp_18(34 DOWNTO 0);

  add_temp_19 <= resize(sum19, 36) + resize(product21, 36);
  sum20 <= add_temp_19(34 DOWNTO 0);

  add_temp_20 <= resize(sum20, 36) + resize(product22, 36);
  sum21 <= add_temp_20(34 DOWNTO 0);

  add_temp_21 <= resize(sum21, 36) + resize(product23, 36);
  sum22 <= add_temp_21(34 DOWNTO 0);

  add_temp_22 <= resize(sum22, 36) + resize(product24, 36);
  sum23 <= add_temp_22(34 DOWNTO 0);

  add_temp_23 <= resize(sum23, 36) + resize(product25, 36);
  sum24 <= add_temp_23(34 DOWNTO 0);

  add_temp_24 <= resize(sum24, 36) + resize(product26, 36);
  sum25 <= add_temp_24(34 DOWNTO 0);

  add_temp_25 <= resize(sum25, 36) + resize(product27, 36);
  sum26 <= add_temp_25(34 DOWNTO 0);

  add_temp_26 <= resize(sum26, 36) + resize(product28, 36);
  sum27 <= add_temp_26(34 DOWNTO 0);

  add_temp_27 <= resize(sum27, 36) + resize(product29, 36);
  sum28 <= add_temp_27(34 DOWNTO 0);

  add_temp_28 <= resize(sum28, 36) + resize(product30, 36);
  sum29 <= add_temp_28(34 DOWNTO 0);

  add_temp_29 <= resize(sum29, 36) + resize(product31, 36);
  sum30 <= add_temp_29(34 DOWNTO 0);

  add_temp_30 <= resize(sum30, 36) + resize(product32, 36);
  sum31 <= add_temp_30(34 DOWNTO 0);

  add_temp_31 <= resize(sum31, 36) + resize(product33, 36);
  sum32 <= add_temp_31(34 DOWNTO 0);

  add_temp_32 <= resize(sum32, 36) + resize(product34, 36);
  sum33 <= add_temp_32(34 DOWNTO 0);

  add_temp_33 <= resize(sum33, 36) + resize(product35, 36);
  sum34 <= add_temp_33(34 DOWNTO 0);

  add_temp_34 <= resize(sum34, 36) + resize(product36, 36);
  sum35 <= add_temp_34(34 DOWNTO 0);

  add_temp_35 <= resize(sum35, 36) + resize(product37, 36);
  sum36 <= add_temp_35(34 DOWNTO 0);

  add_temp_36 <= resize(sum36, 36) + resize(product38, 36);
  sum37 <= add_temp_36(34 DOWNTO 0);

  add_temp_37 <= resize(sum37, 36) + resize(product39, 36);
  sum38 <= add_temp_37(34 DOWNTO 0);

  add_temp_38 <= resize(sum38, 36) + resize(product40, 36);
  sum39 <= add_temp_38(34 DOWNTO 0);

  add_temp_39 <= resize(sum39, 36) + resize(product41, 36);
  sum40 <= add_temp_39(34 DOWNTO 0);

  add_temp_40 <= resize(sum40, 36) + resize(product42, 36);
  sum41 <= add_temp_40(34 DOWNTO 0);

  add_temp_41 <= resize(sum41, 36) + resize(product43, 36);
  sum42 <= add_temp_41(34 DOWNTO 0);

  add_temp_42 <= resize(sum42, 36) + resize(product44, 36);
  sum43 <= add_temp_42(34 DOWNTO 0);

  add_temp_43 <= resize(sum43, 36) + resize(product45, 36);
  sum44 <= add_temp_43(34 DOWNTO 0);

  add_temp_44 <= resize(sum44, 36) + resize(product46, 36);
  sum45 <= add_temp_44(34 DOWNTO 0);

  add_temp_45 <= resize(sum45, 36) + resize(product47, 36);
  sum46 <= add_temp_45(34 DOWNTO 0);

  add_temp_46 <= resize(sum46, 36) + resize(product48, 36);
  sum47 <= add_temp_46(34 DOWNTO 0);

  add_temp_47 <= resize(sum47, 36) + resize(product49, 36);
  sum48 <= add_temp_47(34 DOWNTO 0);

  add_temp_48 <= resize(sum48, 36) + resize(product50, 36);
  sum49 <= add_temp_48(34 DOWNTO 0);

  add_temp_49 <= resize(sum49, 36) + resize(product51, 36);
  sum50 <= add_temp_49(34 DOWNTO 0);

  add_temp_50 <= resize(sum50, 36) + resize(product52, 36);
  sum51 <= add_temp_50(34 DOWNTO 0);

  add_temp_51 <= resize(sum51, 36) + resize(product53, 36);
  sum52 <= add_temp_51(34 DOWNTO 0);

  add_temp_52 <= resize(sum52, 36) + resize(product54, 36);
  sum53 <= add_temp_52(34 DOWNTO 0);

  add_temp_53 <= resize(sum53, 36) + resize(product55, 36);
  sum54 <= add_temp_53(34 DOWNTO 0);

  add_temp_54 <= resize(sum54, 36) + resize(product56, 36);
  sum55 <= add_temp_54(34 DOWNTO 0);

  add_temp_55 <= resize(sum55, 36) + resize(product57, 36);
  sum56 <= add_temp_55(34 DOWNTO 0);

  add_temp_56 <= resize(sum56, 36) + resize(product58, 36);
  sum57 <= add_temp_56(34 DOWNTO 0);

  add_temp_57 <= resize(sum57, 36) + resize(product59, 36);
  sum58 <= add_temp_57(34 DOWNTO 0);

  add_temp_58 <= resize(sum58, 36) + resize(product60, 36);
  sum59 <= add_temp_58(34 DOWNTO 0);

  add_temp_59 <= resize(sum59, 36) + resize(product61, 36);
  sum60 <= add_temp_59(34 DOWNTO 0);

  add_temp_60 <= resize(sum60, 36) + resize(product62, 36);
  sum61 <= add_temp_60(34 DOWNTO 0);

  add_temp_61 <= resize(sum61, 36) + resize(product63, 36);
  sum62 <= add_temp_61(34 DOWNTO 0);

  add_temp_62 <= resize(sum62, 36) + resize(product64, 36);
  sum63 <= add_temp_62(34 DOWNTO 0);

  add_temp_63 <= resize(sum63, 36) + resize(product65, 36);
  sum64 <= add_temp_63(34 DOWNTO 0);

  add_temp_64 <= resize(sum64, 36) + resize(product66, 36);
  sum65 <= add_temp_64(34 DOWNTO 0);

  add_temp_65 <= resize(sum65, 36) + resize(product67, 36);
  sum66 <= add_temp_65(34 DOWNTO 0);

  add_temp_66 <= resize(sum66, 36) + resize(product68, 36);
  sum67 <= add_temp_66(34 DOWNTO 0);

  add_temp_67 <= resize(sum67, 36) + resize(product69, 36);
  sum68 <= add_temp_67(34 DOWNTO 0);

  add_temp_68 <= resize(sum68, 36) + resize(product70, 36);
  sum69 <= add_temp_68(34 DOWNTO 0);

  add_temp_69 <= resize(sum69, 36) + resize(product71, 36);
  sum70 <= add_temp_69(34 DOWNTO 0);

  add_temp_70 <= resize(sum70, 36) + resize(product72, 36);
  sum71 <= add_temp_70(34 DOWNTO 0);

  add_temp_71 <= resize(sum71, 36) + resize(product73, 36);
  sum72 <= add_temp_71(34 DOWNTO 0);

  add_temp_72 <= resize(sum72, 36) + resize(product74, 36);
  sum73 <= add_temp_72(34 DOWNTO 0);

  add_temp_73 <= resize(sum73, 36) + resize(product75, 36);
  sum74 <= add_temp_73(34 DOWNTO 0);

  add_temp_74 <= resize(sum74, 36) + resize(product76, 36);
  sum75 <= add_temp_74(34 DOWNTO 0);

  add_temp_75 <= resize(sum75, 36) + resize(product77, 36);
  sum76 <= add_temp_75(34 DOWNTO 0);

  add_temp_76 <= resize(sum76, 36) + resize(product78, 36);
  sum77 <= add_temp_76(34 DOWNTO 0);

  add_temp_77 <= resize(sum77, 36) + resize(product79, 36);
  sum78 <= add_temp_77(34 DOWNTO 0);

  output_typeconvert <= resize(shift_right(sum78(34 DOWNTO 0) + ( "0" & (sum78(25) & NOT sum78(25) & NOT sum78(25) & NOT sum78(25) & NOT sum78(25) & NOT sum78(25) & NOT sum78(25) & NOT sum78(25) & NOT sum78(25) & NOT sum78(25) & NOT sum78(25) & NOT sum78(25) & NOT sum78(25) & NOT sum78(25) & NOT sum78(25) & NOT sum78(25) & NOT sum78(25) & NOT sum78(25) & NOT sum78(25) & NOT sum78(25) & NOT sum78(25) & NOT sum78(25) & NOT sum78(25) & NOT sum78(25) & NOT sum78(25))), 25), 10);

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= (OTHERS => '0');
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        output_register <= output_typeconvert;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= std_logic_vector(output_register);
END rtl;
